stages:
  - analysis
  - test

analyze-code:
  stage: analysis
  image:
    name: python:3.11-alpine
    pull_policy: always # available: always, if-not-present, never
  before_script:
    - apk update
    - apk upgrade
    - apk add --no-cache bash
    - apk add --update util-linux
    - apk add --no-cache clang-extra-tools
    - apk add git
    - git fetch --depth=1 origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - git switch ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - git pull origin ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - git fetch origin ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    - git switch ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    - git pull origin ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME}
    - echo "$(git branch)"
    - mkdir ./artifacts
  script:
    - echo "Getting changed files ..."
    - bash ./Extras/Shell/GitChangedFiles.sh ${CI_MERGE_REQUEST_TARGET_BRANCH_NAME} ${CI_MERGE_REQUEST_SOURCE_BRANCH_NAME} > ./artifacts/changed-files-list.txt
    - echo "Formatting..."
    - bash ./Extras/Shell/ClangFormat.sh --output-file ./artifacts/lint_fromat.diff --files ./artifacts/changed-files-list.txt
  artifacts:
    when: always
    paths:
      - ./artifacts/changed-files-list.txt
      - ./artifacts/lint_fromat.diff
  only:
    - merge_requests
  tags: [saas-linux-small-amd64]

test-engine:
  stage: test
    image:
      name: debian:bookworm
      pull_policy: always # available: always, if-not-present, never
    variables:
      CI_BUILD_TEST_PRESET: "unit_tests"
      CI_ENGINE_GTEST_EXE: SorexEngineUnitTests
    before_script:
      - apt-get update
      - apt-get -y install clang cmake libgtest-dev
    script:
      - mkdir ./build
      - cmake --version
      - cmake --preset ${CI_BUILD_TEST_PRESET}
      - cmake --build ./build
      - ./build/${CI_BUILD_TEST_PRESET}/Engine/Test/${CI_ENGINE_GTEST_EXE} --gtest_output="xml:./gtest-result.xml"
    artifacts:
      when: always
      reports:
        junit: ./gtest-result.xml
    only:
      - develop
      - main
    tags: [saas-linux-small-amd64]
