name: Code Format

on:
  pull_request:
    branches:
      - '*'

jobs:
  code-format:
    runs-on: ubuntu-latest

    steps:
      - name: Set up bash and clang-tools
        run: |
          sudo apt-get update && sudo apt-get -y install clang-format util-linux clang-extra-tools

      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Fetch target branch
        run: |
          git fetch origin ${{ github.event.pull_request.base.ref }}
          git switch ${{ github.event.pull_request.base.ref }}
          git pull origin ${{ github.event.pull_request.base.ref }}

      - name: Fetch source branch
        run: |
          git fetch origin ${{ github.event.pull_request.head.ref }}
          git switch ${{ github.event.pull_request.head.ref }}
          git pull origin ${{ github.event.pull_request.head.ref }}

      - name: Create artifacts directory
        run: mkdir ./artifacts

      - name: Get git changed files
        run: bash ./Extras/Shell/GitChangedFiles.sh ${{ github.event.pull_request.base.ref }} ${{ github.event.pull_request.head.ref }} > ./artifacts/changed-files-list.txt

      - name: Compare Code Formatting
        run: bash ./Extras/Shell/ClangFormat.sh --output-file ./artifacts/lint_format.diff --files ./artifacts/changed-files-list.txt

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: format-artifacts
          path: |
            ./artifacts/changed-files-list.txt
            ./artifacts/lint_format.diff
